// Applies REIP-approved SEO changes to this static site at build time.
// Generated by REIP's microsite onboarding — see seo/reip.config.json for the
// project id + manifest token (read-only, project-scoped) this script uses.
//
// Two sources, both additive/safe by design (REIP never auto-applies a price
// or RERA number — those stay pending for human review):
//   1. seo/metadata.json — REIP's copy PRs (title/meta description) land here,
//      keyed by route. Only fields actually present for a route are applied.
//   2. The REIP schema manifest (fetched using the token in reip.config.json)
//      — approved JSON-LD, merged into <head> alongside any existing
//      hand-authored schema. Exact-duplicate blocks are skipped so repeat
//      builds don't pile up copies, and for singleton types (FAQPage,
//      Organization, …) the approved block supersedes a hand-authored block
//      of the same type so the page never ships two competing copies.
//
// No dependencies beyond Node built-ins.

import { readFile, writeFile, readdir } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();

async function readJsonSafe(relPath, fallback) {
  try {
    const raw = await readFile(path.join(ROOT, relPath), "utf8");
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

async function readTextSafe(relPath) {
  try {
    return await readFile(path.join(ROOT, relPath), "utf8");
  } catch {
    return null;
  }
}

/** Discover every .html file under the repo root, skipping node_modules/.git. */
async function discoverHtmlFiles(dir = ROOT, out = []) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name === ".git" || entry.name.startsWith(".")) {
      continue;
    }
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      await discoverHtmlFiles(full, out);
    } else if (entry.name.endsWith(".html")) {
      out.push(full);
    }
  }
  return out;
}

/** file path -> route, e.g. index.html -> "/", about.html -> "/about", blog/index.html -> "/blog". */
function routeForFile(filePath) {
  const rel = path.relative(ROOT, filePath).replace(/\\/g, "/");
  if (rel === "index.html") return "/";
  if (rel.endsWith("/index.html")) return "/" + rel.slice(0, -"/index.html".length);
  return "/" + rel.replace(/\.html$/, "");
}

async function fetchManifest(config) {
  if (!config?.manifest_token) {
    console.log("[apply-seo] no manifest token in seo/reip.config.json — skipping schema injection.");
    return { pages: [] };
  }
  try {
    const res = await fetch(`${config.api_url}/v1/projects/${config.project_id}/seo-manifest`, {
      headers: { authorization: `Bearer ${config.manifest_token}` },
    });
    if (!res.ok) {
      console.warn(`[apply-seo] manifest fetch failed: ${res.status} — continuing without schema.`);
      return { pages: [] };
    }
    const body = await res.json();
    return body.data ?? { pages: [] };
  } catch (err) {
    console.warn("[apply-seo] manifest fetch errored — continuing without schema:", err.message);
    return { pages: [] };
  }
}

// Fetches the live sitemap.xml (raw XML, not JSON — same bearer token as the
// manifest) and writes it to the repo root. Returns the sitemap's own URL
// (derived from its first <loc>, which the server already computes from a
// real property's canonical_url) so mergeRobotsTxt can point at it with an
// absolute URL, as robots.txt's Sitemap: directive requires — never null on
// success, only on any failure, matching fetchManifest's never-fail posture.
// Derives the absolute sitemap URL (origin + /sitemap.xml) from a sitemap's
// first <loc>, or null if it has none. Used to point robots.txt at whichever
// sitemap actually survives — the freshly fetched one or the committed one.
function sitemapUrlFromXml(xml) {
  const firstLoc = xml && xml.match(/<loc>([^<]+)<\/loc>/);
  if (!firstLoc) return null;
  try {
    return `${new URL(firstLoc[1]).origin}/sitemap.xml`;
  } catch {
    return null;
  }
}

async function fetchAndWriteSitemap(config) {
  if (!config?.manifest_token) {
    console.log("[apply-seo] no manifest token in seo/reip.config.json — skipping sitemap.");
    return sitemapUrlFromXml(await readTextSafe("sitemap.xml"));
  }
  try {
    const res = await fetch(`${config.api_url}/v1/projects/${config.project_id}/sitemap.xml`, {
      headers: { authorization: `Bearer ${config.manifest_token}` },
    });
    if (!res.ok) {
      console.warn(`[apply-seo] sitemap fetch failed: ${res.status} — keeping existing sitemap.xml.`);
      return sitemapUrlFromXml(await readTextSafe("sitemap.xml"));
    }
    const xml = await res.text();
    // Never overwrite a good committed sitemap with a URL-less one. The API
    // returns an empty <urlset> when the project has no active property yet;
    // clobbering the generator's real sitemap with that empties the live
    // sitemap, which is strictly worse than leaving the committed one in
    // place. Only write when the fetched sitemap actually has URLs.
    if (!/<loc>/.test(xml)) {
      console.warn("[apply-seo] fetched sitemap has no <loc> entries — keeping existing sitemap.xml.");
      return sitemapUrlFromXml(await readTextSafe("sitemap.xml"));
    }
    await writeFile(path.join(ROOT, "sitemap.xml"), xml, "utf8");
    console.log("[apply-seo] wrote sitemap.xml");
    return sitemapUrlFromXml(xml);
  } catch (err) {
    console.warn("[apply-seo] sitemap fetch errored — keeping existing sitemap.xml:", err.message);
    return sitemapUrlFromXml(await readTextSafe("sitemap.xml"));
  }
}

// Adds a Sitemap: line to robots.txt without disturbing anything already
// there (crawl-delay rules, per-bot Disallow lines, an already-hand-authored
// Sitemap: line, etc.) — only appends when no matching line exists yet.
// Creates a minimal robots.txt when none exists at all.
async function mergeRobotsTxt(sitemapUrl) {
  if (!sitemapUrl) return;
  const normalize = (url) => url.trim().replace(/\/+$/, "").toLowerCase();
  const target = normalize(sitemapUrl);

  const existing = await readTextSafe("robots.txt");
  if (existing === null) {
    const content = `User-agent: *\nAllow: /\nSitemap: ${sitemapUrl}\n`;
    await writeFile(path.join(ROOT, "robots.txt"), content, "utf8");
    console.log("[apply-seo] created robots.txt with Sitemap: line");
    return;
  }

  const alreadyPresent = existing
    .split(/\r?\n/)
    .some((line) => {
      const match = line.match(/^\s*sitemap\s*:\s*(.+)$/i);
      return match && normalize(match[1]) === target;
    });
  if (alreadyPresent) return;

  const separator = existing.endsWith("\n") ? "" : "\n";
  await writeFile(
    path.join(ROOT, "robots.txt"),
    `${existing}${separator}Sitemap: ${sitemapUrl}\n`,
    "utf8",
  );
  console.log("[apply-seo] appended Sitemap: line to existing robots.txt");
}

function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function applyTitle(html, title) {
  if (!title) return html;
  return html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${escapeHtml(title)}</title>`);
}

function applyMetaDescription(html, description) {
  if (!description) return html;
  return html.replace(
    /(<meta\s+name=["']description["']\s+content=)["'][\s\S]*?["']/i,
    `$1"${escapeHtml(description)}"`,
  );
}

// Schema.org types that must appear at most once per page. Google's Rich
// Results treats a second block of one of these as a conflict and can ignore
// the whole set, so when the approved manifest supplies one we drop any
// hand-authored block of the same type and let the (reviewed, usually richer)
// manifest block win — leaving exactly one block of that type on the page.
const SINGLETON_SCHEMA_TYPES = new Set([
  "FAQPage",
  "Organization",
  "WebSite",
  "BreadcrumbList",
  "RealEstateListing",
]);

function schemaTypeOf(block) {
  const t = block && block["@type"];
  return typeof t === "string" ? t : null;
}

function appendSchema(html, jsonLdBlocks) {
  if (!jsonLdBlocks || jsonLdBlocks.length === 0) return html;

  const existing = [
    ...html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g),
  ].map((m) => {
    let json = null;
    try {
      json = JSON.parse(m[1]);
    } catch {
      json = null;
    }
    return { raw: m[0], json, canon: json ? JSON.stringify(json) : null };
  });

  // Singleton types the manifest is about to supply — a hand-authored block of
  // one of these gets removed so it can't compete with the approved block.
  const manifestSingletons = new Set(
    jsonLdBlocks.map(schemaTypeOf).filter((t) => t && SINGLETON_SCHEMA_TYPES.has(t)),
  );

  let out = html;
  const survivors = [];
  for (const block of existing) {
    const t = schemaTypeOf(block.json);
    if (t && manifestSingletons.has(t)) {
      // String (not regex) replace — raw is matched literally, removed once.
      out = out.replace(block.raw, "");
    } else {
      survivors.push(block);
    }
  }

  // Skip manifest blocks byte-identical to one that survived, so repeat builds
  // don't pile up copies.
  const survivingCanon = new Set(survivors.map((b) => b.canon).filter(Boolean));
  const toAdd = jsonLdBlocks.filter((b) => !survivingCanon.has(JSON.stringify(b)));
  if (toAdd.length === 0) return out;

  const scriptTags = toAdd
    .map((b) => `<script type="application/ld+json">\n${JSON.stringify(b, null, 2)}\n</script>`)
    .join("\n");
  return out.replace(/<\/head>/i, `\n<!-- REIP: approved schema, auto-injected at build time -->\n${scriptTags}\n</head>`);
}

async function applyToFile(filePath, route, metadataForRoute, manifestPage) {
  let html;
  try {
    html = await readFile(filePath, "utf8");
  } catch {
    return;
  }
  let updated = html;
  if (metadataForRoute?.title) updated = applyTitle(updated, metadataForRoute.title);
  if (metadataForRoute?.meta_description) updated = applyMetaDescription(updated, metadataForRoute.meta_description);
  if (manifestPage?.json_ld) updated = appendSchema(updated, manifestPage.json_ld);
  if (updated !== html) {
    await writeFile(filePath, updated, "utf8");
    console.log(`[apply-seo] updated ${path.relative(ROOT, filePath)} (route ${route})`);
  }
}

async function main() {
  const fileConfig = await readJsonSafe("seo/reip.config.json", null);
  // Secrets belong in the deployment environment, never in a tracked config file.
  const config = fileConfig
    ? { ...fileConfig, manifest_token: process.env.REIP_MANIFEST_TOKEN || "" }
    : null;
  const metadata = await readJsonSafe("seo/metadata.json", {});
  const manifest = await fetchManifest(config);
  const manifestByRoute = new Map((manifest.pages ?? []).map((p) => [p.path, p]));

  const htmlFiles = await discoverHtmlFiles();
  for (const filePath of htmlFiles) {
    const route = routeForFile(filePath);
    await applyToFile(filePath, route, metadata[route], manifestByRoute.get(route));
  }

  const sitemapUrl = await fetchAndWriteSitemap(config);
  await mergeRobotsTxt(sitemapUrl);
}

main().catch((err) => {
  // Never fail the deploy over an SEO-application error — the generated site
  // is still valid and should ship. Log loudly instead.
  console.error("[apply-seo] unexpected error, continuing build unmodified:", err);
});
